-- =============================================================
-- Nestoria — patch: real images + correct password hash
-- Auto-generated by scripts/upload-images.js. Re-run that script if
-- you change the manifest. Safe to apply against an already-seeded
-- database (idempotent UPDATE statements).
-- =============================================================

-- 1. Fix the dummy bcrypt hash from the original seed (the placeholder
--    did NOT actually hash 'password123'). Real hash for 'password123':
UPDATE customers SET password_hash = '$2b$10$R/BokQK3A3VqA6amtJlYUepO5dIf4x9e8ZHYZc9UOmiRXZSifX5CK'
  WHERE password_hash = '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy';
UPDATE hosts SET password_hash = '$2b$10$R/BokQK3A3VqA6amtJlYUepO5dIf4x9e8ZHYZc9UOmiRXZSifX5CK'
  WHERE password_hash = '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy';

-- 2. Hotel hero images + room images + gallery rows

UPDATE hotels SET hero_image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/marigold-house/hero.jpg' WHERE slug = 'marigold-house';
DELETE FROM hotel_images WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'marigold-house');
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/marigold-house/gallery-1.jpg', 0, NULL FROM hotels WHERE slug = 'marigold-house';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/marigold-house/gallery-2.jpg', 1, NULL FROM hotels WHERE slug = 'marigold-house';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/marigold-house/gallery-3.jpg', 2, NULL FROM hotels WHERE slug = 'marigold-house';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/marigold-house/gallery-4.jpg', 3, NULL FROM hotels WHERE slug = 'marigold-house';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/marigold-house/heritage-suite.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'marigold-house') AND type = 'Heritage Suite';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/marigold-house/garden-room.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'marigold-house') AND type = 'Garden Room';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/marigold-house/maharaja-suite.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'marigold-house') AND type = 'Maharaja Suite';

UPDATE hotels SET hero_image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/aravali-retreat/hero.jpg' WHERE slug = 'aravali-retreat';
DELETE FROM hotel_images WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'aravali-retreat');
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/aravali-retreat/gallery-1.jpg', 0, NULL FROM hotels WHERE slug = 'aravali-retreat';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/aravali-retreat/gallery-2.jpg', 1, NULL FROM hotels WHERE slug = 'aravali-retreat';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/aravali-retreat/gallery-3.jpg', 2, NULL FROM hotels WHERE slug = 'aravali-retreat';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/aravali-retreat/gallery-4.jpg', 3, NULL FROM hotels WHERE slug = 'aravali-retreat';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/aravali-retreat/pine-cabin.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'aravali-retreat') AND type = 'Pine Cabin';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/aravali-retreat/stargazer-suite.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'aravali-retreat') AND type = 'Stargazer Suite';

UPDATE hotels SET hero_image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/casa-pamparo/hero.jpg' WHERE slug = 'casa-pamparo';
DELETE FROM hotel_images WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'casa-pamparo');
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/casa-pamparo/gallery-1.jpg', 0, NULL FROM hotels WHERE slug = 'casa-pamparo';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/casa-pamparo/gallery-2.jpg', 1, NULL FROM hotels WHERE slug = 'casa-pamparo';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/casa-pamparo/gallery-3.jpg', 2, NULL FROM hotels WHERE slug = 'casa-pamparo';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/casa-pamparo/gallery-4.jpg', 3, NULL FROM hotels WHERE slug = 'casa-pamparo';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/casa-pamparo/pool-suite.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'casa-pamparo') AND type = 'Pool Suite';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/casa-pamparo/garden-room.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'casa-pamparo') AND type = 'Garden Room';

UPDATE hotels SET hero_image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/postcard-munnar/hero.jpg' WHERE slug = 'postcard-munnar';
DELETE FROM hotel_images WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'postcard-munnar');
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/postcard-munnar/gallery-1.jpg', 0, NULL FROM hotels WHERE slug = 'postcard-munnar';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/postcard-munnar/gallery-2.jpg', 1, NULL FROM hotels WHERE slug = 'postcard-munnar';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/postcard-munnar/gallery-3.jpg', 2, NULL FROM hotels WHERE slug = 'postcard-munnar';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/postcard-munnar/gallery-4.jpg', 3, NULL FROM hotels WHERE slug = 'postcard-munnar';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/postcard-munnar/tea-cabin.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'postcard-munnar') AND type = 'Tea Cabin';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/postcard-munnar/cloud-suite.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'postcard-munnar') AND type = 'Cloud Suite';

UPDATE hotels SET hero_image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/the-salt-house/hero.jpg' WHERE slug = 'the-salt-house';
DELETE FROM hotel_images WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'the-salt-house');
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/the-salt-house/gallery-1.jpg', 0, NULL FROM hotels WHERE slug = 'the-salt-house';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/the-salt-house/gallery-2.jpg', 1, NULL FROM hotels WHERE slug = 'the-salt-house';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/the-salt-house/gallery-3.jpg', 2, NULL FROM hotels WHERE slug = 'the-salt-house';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/the-salt-house/gallery-4.jpg', 3, NULL FROM hotels WHERE slug = 'the-salt-house';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/the-salt-house/sea-suite.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'the-salt-house') AND type = 'Sea Suite';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/the-salt-house/plunge-room.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'the-salt-house') AND type = 'Plunge Room';

UPDATE hotels SET hero_image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/silk-route-inn/hero.jpg' WHERE slug = 'silk-route-inn';
DELETE FROM hotel_images WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'silk-route-inn');
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/silk-route-inn/gallery-1.jpg', 0, NULL FROM hotels WHERE slug = 'silk-route-inn';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/silk-route-inn/gallery-2.jpg', 1, NULL FROM hotels WHERE slug = 'silk-route-inn';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/silk-route-inn/gallery-3.jpg', 2, NULL FROM hotels WHERE slug = 'silk-route-inn';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/silk-route-inn/gallery-4.jpg', 3, NULL FROM hotels WHERE slug = 'silk-route-inn';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/silk-route-inn/fort-room.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'silk-route-inn') AND type = 'Fort Room';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/silk-route-inn/rooftop-suite.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'silk-route-inn') AND type = 'Rooftop Suite';

UPDATE hotels SET hero_image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/house-of-cardamom/hero.jpg' WHERE slug = 'house-of-cardamom';
DELETE FROM hotel_images WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'house-of-cardamom');
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/house-of-cardamom/gallery-1.jpg', 0, NULL FROM hotels WHERE slug = 'house-of-cardamom';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/house-of-cardamom/gallery-2.jpg', 1, NULL FROM hotels WHERE slug = 'house-of-cardamom';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/house-of-cardamom/gallery-3.jpg', 2, NULL FROM hotels WHERE slug = 'house-of-cardamom';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/house-of-cardamom/gallery-4.jpg', 3, NULL FROM hotels WHERE slug = 'house-of-cardamom';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/house-of-cardamom/wallace-room.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'house-of-cardamom') AND type = 'Wallace Room';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/house-of-cardamom/pepper-suite.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'house-of-cardamom') AND type = 'Pepper Suite';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/house-of-cardamom/estate-bungalow.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'house-of-cardamom') AND type = 'Estate Bungalow';

UPDATE hotels SET hero_image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/indigo-lodge/hero.jpg' WHERE slug = 'indigo-lodge';
DELETE FROM hotel_images WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'indigo-lodge');
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/indigo-lodge/gallery-1.jpg', 0, NULL FROM hotels WHERE slug = 'indigo-lodge';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/indigo-lodge/gallery-2.jpg', 1, NULL FROM hotels WHERE slug = 'indigo-lodge';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/indigo-lodge/gallery-3.jpg', 2, NULL FROM hotels WHERE slug = 'indigo-lodge';
INSERT INTO hotel_images (hotel_id, url, position, caption) SELECT id, 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/hotels/indigo-lodge/gallery-4.jpg', 3, NULL FROM hotels WHERE slug = 'indigo-lodge';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/indigo-lodge/earth-cabin.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'indigo-lodge') AND type = 'Earth Cabin';
UPDATE rooms SET image_url = 'https://twsdesejcimvmrbopdwj.supabase.co/storage/v1/object/public/hotel-images/rooms/indigo-lodge/indigo-suite.jpg' WHERE hotel_id = (SELECT id FROM hotels WHERE slug = 'indigo-lodge') AND type = 'Indigo Suite';

