#!/usr/bin/env node
// Download curated Unsplash photos and upload them to the project's Supabase bucket,
// then emit a SQL file with UPDATE statements that populate hero_image_url, image_url,
// and hotel_images rows.
//
// Run once:
//   node scripts/upload-images.js
//
// Reads SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY + SUPABASE_BUCKET_NAME from backend/.env.

const path = require('path');
const fs = require('fs');

require('dotenv').config({ path: path.join(__dirname, '..', 'backend', '.env') });

const { createClient } = require('@supabase/supabase-js');
const manifest = require('./image-manifest');

const SUPABASE_URL = process.env.SUPABASE_URL;
const SERVICE_KEY  = process.env.SUPABASE_SERVICE_ROLE_KEY;
const BUCKET       = process.env.SUPABASE_BUCKET_NAME || 'hotel-images';

if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error('SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY missing in backend/.env');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false } });

function roomSlug(type) {
  return type.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function sqlEscape(s) {
  return s.replace(/'/g, "''");
}

async function fetchBuffer(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`fetch ${url} → ${res.status}`);
  const ab = await res.arrayBuffer();
  return Buffer.from(ab);
}

async function uploadOne(srcUrl, destPath) {
  const buf = await fetchBuffer(srcUrl);
  const { error } = await supabase.storage
    .from(BUCKET)
    .upload(destPath, buf, { contentType: 'image/jpeg', upsert: true });
  if (error) throw error;
  const { data } = supabase.storage.from(BUCKET).getPublicUrl(destPath);
  return data.publicUrl;
}

(async () => {
  const sql = [];
  sql.push('-- =============================================================');
  sql.push('-- Nestoria — patch: real images + correct password hash');
  sql.push('-- Auto-generated by scripts/upload-images.js. Re-run that script if');
  sql.push('-- you change the manifest. Safe to apply against an already-seeded');
  sql.push('-- database (idempotent UPDATE statements).');
  sql.push('-- =============================================================');
  sql.push('');
  sql.push("-- 1. Fix the dummy bcrypt hash from the original seed (the placeholder");
  sql.push("--    did NOT actually hash 'password123'). Real hash for 'password123':");
  sql.push("UPDATE customers SET password_hash = '$2b$10$R/BokQK3A3VqA6amtJlYUepO5dIf4x9e8ZHYZc9UOmiRXZSifX5CK'");
  sql.push("  WHERE password_hash = '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy';");
  sql.push("UPDATE hosts SET password_hash = '$2b$10$R/BokQK3A3VqA6amtJlYUepO5dIf4x9e8ZHYZc9UOmiRXZSifX5CK'");
  sql.push("  WHERE password_hash = '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy';");
  sql.push('');
  sql.push('-- 2. Hotel hero images + room images + gallery rows');
  sql.push('');

  let count = 0;
  for (const h of manifest) {
    console.log(`\n→ ${h.slug}`);

    // Hero
    const heroPath = `hotels/${h.slug}/hero.jpg`;
    const heroUrl  = await uploadOne(h.hero, heroPath);
    count++; process.stdout.write(`  ✓ hero\n`);
    sql.push(`UPDATE hotels SET hero_image_url = '${sqlEscape(heroUrl)}' WHERE slug = '${h.slug}';`);

    // Gallery (clear existing rows for this hotel first)
    sql.push(`DELETE FROM hotel_images WHERE hotel_id = (SELECT id FROM hotels WHERE slug = '${h.slug}');`);
    for (let i = 0; i < h.gallery.length; i++) {
      const gPath = `hotels/${h.slug}/gallery-${i + 1}.jpg`;
      const gUrl  = await uploadOne(h.gallery[i], gPath);
      count++; process.stdout.write(`  ✓ gallery ${i + 1}\n`);
      sql.push(
        `INSERT INTO hotel_images (hotel_id, url, position, caption) ` +
        `SELECT id, '${sqlEscape(gUrl)}', ${i}, NULL FROM hotels WHERE slug = '${h.slug}';`
      );
    }

    // Rooms
    for (const r of h.rooms) {
      const rs = roomSlug(r.type);
      const rPath = `rooms/${h.slug}/${rs}.jpg`;
      const rUrl  = await uploadOne(r.url, rPath);
      count++; process.stdout.write(`  ✓ room: ${r.type}\n`);
      sql.push(
        `UPDATE rooms SET image_url = '${sqlEscape(rUrl)}' ` +
        `WHERE hotel_id = (SELECT id FROM hotels WHERE slug = '${h.slug}') AND type = '${sqlEscape(r.type)}';`
      );
    }
    sql.push('');
  }

  const outPath = path.join(__dirname, '..', 'database', '005_seed_images.sql');
  fs.writeFileSync(outPath, sql.join('\n') + '\n', 'utf8');
  console.log(`\nUploaded ${count} images. SQL written to ${outPath}`);
})().catch((err) => {
  console.error('\nFAILED:', err);
  process.exit(1);
});
