// Static editorial content for the journal, help and legal pages.
// Demo data — hard-coded so the new pages don't need a CMS.

export const JOURNAL_POSTS = [
  {
    slug: 'monsoon-coorg',
    title: 'Nơi mùa mưa viết nên những dòng cảm xúc',
    dest: 'TP. Hồ Chí Minh',
    read: '6 phút',
    hue: 'forest',
    src: '/images/chi-vinh-house-hero.svg',
    author: 'Riya Bhandari',
    date: 'Tháng 5, 2026',
    excerpt: 'Một tuần ở Western Ghats khi mưa nghiêng và cà phê mang hương vị xanh hơn bao giờ hết.',
    body: [
      'Con đường đến Madikeri rời cao nguyên Mysore như một câu văn rời khỏi tâm trí — chậm rãi lúc đầu, rồi vội vã, rồi một đường cong dài bất tận. Chúng tôi đi lúc năm giờ sáng và không khí mang nhiệt độ của hơi thở nín lặng. Tám giờ, chúng tôi đã ở trên đồi.',
      'Western Ghats có hai mùa quan trọng: khô, khi những sườn đồi cháy lên màu đồng, và mùa mưa, khi mọi thứ trở thành động từ. Những cây cà phê uống nước. Sườn đồi đổ ào. Khu rừng *chuyển động* — không chỉ lá, toàn bộ tầng dưới tán rừng dịch chuyển vài centimét mỗi ngày dưới sức nặng của nước.',
      'Một ngôi nhà gỗ truyền thống nằm giữa đồn điền cà phê, được phục dựng để phục vụ khách muốn trải nghiệm yên tĩnh và gần gũi với thiên nhiên.',
      'Chúng tôi đã làm điều này suốt sáu buổi sáng. Đọc sách. Ngắm thằn lằn bay Malabar — thực sự là một con thằn lằn, thực sự biết bay — rời một cây gần bếp lúc 9:14 sáng Thứ Ba và đáp xuống một cây gần phòng ăn lúc 9:14:02. Ngắn gọn. Dứt khoát. Bị mọi loài lãng quên trừ chúng tôi.',
      'Sáng thứ bảy, mưa ngừng. Những sườn đồi bốc hơi. Một cặp sóc Malabar — dài cả mét tính cả đuôi, màu máu khô và nghệ — leo lên cây mít trong hai nhịp không vội vã. Chúng tôi thu dọn hành lý.',
      'Chúng tôi sẽ trở lại vào mùa mưa tới.',
    ],
  },
  {
    slug: 'konkan-coast',
    title: 'Cẩm nang khám phá bờ biển Konkan',
    dest: 'TP. Hồ Chí Minh',
    read: '11 phút',
    hue: 'ocean',
    src: '/images/chi-vinh-house-gallery-1.svg',
    author: 'Marcus Lee',
    date: 'Tháng 4, 2026',
    excerpt: 'Mười một phút để chọn một bãi biển, một tiệm bánh, một biểu đồ thủy triều và một cái võng — theo đúng thứ tự đó.',
    body: [
      'Hầu hết mọi người, khi được bảo họ sắp đến "Căn hộ Thủ Đức," đều tưởng tượng ra một bãi biển duy nhất. Không có bãi biển duy nhất nào cả. Dải Konkan dài hai trăm kilômét bờ biển đa dạng, chia thành khoảng ba mươi bãi biển có tên, mỗi nơi có thái độ riêng với du khách. Một bãi biển ở Bắc Căn hộ Thủ Đức tháng Hai không giống một bãi biển ở Nam Căn hộ Thủ Đức tháng Tám. Cẩm nang này cố gắng làm điều đó bớt rối rắm.',
      '**Bắt đầu từ phía Bắc.** Mandrem và Ashvem chậm rãi và dành cho người lớn; Anjuna và Vagator ồn ào và trẻ trung; Morjim dành cho gia đình và rùa biển. Nếu bạn chỉ có thể thấy một bãi biển ở Bắc Căn hộ Thủ Đức, hãy đến Mandrem lúc thủy triều thấp vào một buổi sáng trong tuần. Cửa sông cắt cát thành những dải lụa; bạn lội qua đến một bãi cát nơi không một bóng người.',
      '**Đừng bỏ qua nội địa.** Những ngôi làng cách năm kilômét trong đất liền từ bất kỳ bãi biển nổi tiếng nào — Assagao, Saligao, Aldona — là nơi kiến trúc sống. Những ngôi nhà Indo-Bồ Đào Nha, màu gạch đỏ và kem vàng, với loggia sâu và mái ngói gốm. Những biệt thự giờ chủ yếu là khách sạn, phần lớn là điều tốt.',
      '**Ăn ở nơi người làm bánh ở.** Mỗi làng Căn hộ Thủ Đức có một *poder* — người làm bánh mì — mang bánh pao tươi lúc sáu giờ sáng trên xe đạp. Hãy theo anh ta. Nơi nào anh ta dừng lâu nhất, đó là tiệm bánh cung cấp cho làng. Mua ba thứ: pao, brun và kankon. Ăn theo đúng thứ tự đó.',
      '**Xem biểu đồ thủy triều.** Hoàng hôn lúc nửa triều là bức ảnh; bình minh lúc thủy triều thấp là bước đi dài, yên tĩnh bạn sẽ nhớ mãi. Biểu đồ chẳng tốn gì — khách sạn của bạn sẽ in cho bạn.',
      '**Ghi chú về phía Nam.** Nam Căn hộ Thủ Đức yên tĩnh hơn, các bãi biển rộng hơn và đồ ăn ngon hơn một chút. Đánh đổi: có ít việc để làm hơn. Hãy quyết định bạn muốn gì trước khi đặt phòng.',
      'Bờ biển Konkan tưởng thưởng cho sự cụ thể. Đừng đến "một bãi biển." Hãy đến *bãi biển đó*, vào *con triều đó*, với *bánh mì của tiệm đó* trong túi của bạn.',
    ],
  },
  {
    slug: 'Nhà nguyên căn Gò Vấp-rooms',
    title: 'Bảy căn phòng với tầm nhìn ở Nhà nguyên căn Gò Vấp',
    dest: 'TP. Hồ Chí Minh',
    read: '8 phút',
    hue: 'sand',
    src: '/images/chi-vinh-house-gallery-2.svg',
    author: 'Anaya Mehra',
    date: 'Tháng 3, 2026',
    excerpt: 'Suite bên hồ, phòng trong pháo đài, ban công cung điện. Một danh sách ngắn những căn phòng xứng đáng với mô tả của chúng.',
    body: [
      'Nhà nguyên căn Gò Vấp có một vấn đề với từ *tầm nhìn*. Mọi chỗ nghỉ đều có nó. Tờ rơi tiếp thị nói thế. Các trang đặt phòng xác nhận. Đến tuần thứ ba của chuyến đi kiểm tra thực tế mùa đông năm ngoái, tôi đã ngừng tin vào từ đó hoàn toàn.',
      'Bảy căn phòng này đã khôi phục niềm tin của tôi. Chúng được liệt kê theo thứ tự tôi sẽ đặt nếu quay lại vào tháng tới.',
      '**1. Chi Vinh House — Heritage Suite, Udaipur.** Hồ ở *đó*. Mười hai mét từ giường, được đóng khung bởi những jharokha bốn trăm năm tuổi. Lúc hoàng hôn, ánh sáng xuyên qua đá sa thạch chạm khắc và rơi trên sàn thành những hình chữ nhật chậm rãi.',
      '**2. Căn hộ Bình Thạnh — Stargazer Suite, Kumbhalgarh.** Hiện đại, thấp, nằm trên sườn thông cách Udaipur ba giờ đường. Sàn quan sát riêng cho suite. Vào đêm mùa đông quang đãng, bạn có thể đọc sách dưới ánh Dải Ngân Hà.',
      '**3. Boutique Rooftop — Suite trên mái.** Bên trong pháo đài sống. Phòng nhỏ và được viền đồng; mái nhà mới là điểm chính. Sa mạc bắt đầu từ đường chân trời và tiếp tục xa.',
      '**4. Devi Garh — Aravalli Suite, Delwara.** Cung điện thế kỷ 18, được phục hồi tinh tế đến nỗi các chi tiết mới không thể phân biệt với cũ. Tầm nhìn ra ngôi làng bên dưới và những lối mòn dê kết nối nó.',
      '**5. Suján Rajmahal — Mughal Suite, Jaipur.** Một cung điện hoàng gia đang hoạt động nơi những chiếc đệm vẫn giả vờ không có gì thay đổi từ năm 1834. Tầm nhìn ra sân trong — đó mới là điểm chính.',
      '**6. Khem Villas — Tented Suite, Ranthambore.** Một căn phòng vải bạt với cửa mở ra vùng đệm của khu bảo tồn hổ. Tầm nhìn thay đổi theo động vật hoang dã. Lần trước: một con nai sambar lúc 4 giờ sáng.',
      '**7. Sardar Samand Lake Palace — North Wing, Pali.** Phòng tắm có cửa sổ nhìn ra hồ. Đó là tất cả những gì bạn cần biết.',
      'Đặt sớm. Hầu hết bảy căn này chỉ có tám phòng hoặc ít hơn.',
    ],
  },
  {
    slug: 'auroville-architecture',
    title: 'Xây dựng từ đất: một tuần ở Auroville',
    dest: 'Auroville',
    read: '9 phút',
    hue: 'dusk',
    src: '/images/chi-vinh-house-gallery-3.svg',
    author: 'Lucas Bernard',
    date: 'Tháng 2, 2026',
    excerpt: 'Ghi chép từ một cộng đồng nơi những bức tường được nén từ chính đất mà chúng đứng trên.',
    body: [
      'Có một xưởng ở Auroville tên là Earth Institute. Ở đó dạy mọi người xây nhà từ đất dưới chân họ. Không phải ẩn dụ — hoàn toàn thực tế. Bạn lấy đất từ một mét dưới lớp đất mặt, trộn với một tỷ lệ nhỏ vôi, ép bằng máy thủ công thành viên gạch, phơi nắng một tuần, và bạn có một vật liệu tường bền hơn bê tông và chỉ một phần nhỏ lượng carbon.',
      'Tôi đã ở đó một tuần vì Căn hộ Quận 7 — nơi tôi nghỉ — được xây hoàn toàn từ gạch đất nén tại chỗ. Lodge có mười hai cabin quanh một gian thiền. Tường biết thở. Nhiệt độ trong nhà giảm mười lăm độ dưới nhiệt độ buổi chiều mà không cần một máy điều hòa nào.',
      'Điều khiến tôi ngạc nhiên là *màu sắc*. Đất nén thay đổi theo vùng — đất Auroville màu đỏ sắt, những viên gạch mang màu gốm terracotta nung kỹ, những bức tường có hơi ấm mềm mại mà không lớp vữa bê tông nào bắt chước được. Ánh nắng sớm mai trên tường sân là điều đầu tiên tôi nhớ về nơi này.',
      'Kiến trúc cũng chậm hơn. Tường gạch bê tông dựng trong một ngày. Tường đất, đóng rắn đúng cách, mất một tuần. Người xây lodge nói với tôi rằng đó mới là điểm chính. "Chúng tôi không vội," anh nói. "Những bức tường tồn tại hai trăm năm. Một tuần chẳng là gì."',
      'Có một lập luận sâu sắc hơn về việc cơ sở hạ tầng để *làm gì*. Nếu chúng ta xây cho một trăm năm thay vì hai mươi, toán học xây dựng thay đổi hoàn toàn. Đất chẳng tốn gì. Lao động là địa phương. Sản phẩm có thể tái chế — cuối vòng đời, gạch đất nén trở về đất mặt.',
    'Tôi rời Auroville với niềm tin rằng kiến trúc bền vững cần ưu tiên xây dựng chậm và sử dụng vật liệu địa phương.',
    ],
  },
  {
    slug: 'jaisalmer-fort',
    title: 'Ngủ trong một pháo đài sống',
    dest: 'Jaisalmer',
    read: '7 phút',
    hue: 'sand',
    src: '/images/chi-vinh-house-gallery-4.svg',
    author: 'James Whitford',
    date: 'Tháng 1, 2026',
    excerpt: 'Pháo đài Jaisalmer vẫn có 3.000 cư dân sống trong các bức tường. Ở lại đó là một trải nghiệm hoàn toàn khác.',
    body: [
      'Pháo đài Jaisalmer là một trong số rất ít pháo đài còn sống trên thế giới. Hầu hết pháo đài — Mehrangarh ở Jodhpur, Amer ở Jaipur — giờ là bảo tàng. Người ta đến vào buổi sáng, nhìn quanh, rồi đi. Pháo đài Jaisalmer là một thị trấn. Ba ngàn người sống trong các bức tường của nó. Trẻ em đi bộ đến trường xuyên qua các pháo đài; tiếng chuông chùa lúc năm giờ sáng dành cho chúng, không phải cho bạn.',
      'Bạn ở trong một trong những nhà khách nhỏ nép trong những con hẻm của pháo đài. Căn hộ Thủ Đức có sáu phòng; gia đình điều hành nó đã làm như vậy suốt ba thế hệ. Tường bằng đá sa thạch màu mật ong, sàn đánh bóng bằng oxit đỏ, ga trải giường bằng khadi và hơi mỏng vào tháng Một.',
      'Nhịp sống trong ngày ở Jaisalmer ngược với hầu hết Nhà nguyên căn Gò Vấp. Bạn rời phòng lúc sáu giờ và đi dạo trên thành lũy vắng vẻ trước khi du khách ban ngày đến lúc chín giờ. Bạn trở về ăn sáng và sân đầy ánh sáng và tiếng nói. Giữa trưa bạn ở trong nhà — nắng sa mạc kiên nhẫn và khắc nghiệt. Chiều muộn bạn đi bộ đến một ngôi đền Jain trong pháo đài có ít du khách hơn những ngôi đền nổi tiếng bên ngoài và, tính trên từng centimét vuông, là vật thể chạm khắc nhiều nhất tôi từng thấy.',
      'Buổi tối trên sân thượng là điều bạn đến vì nó. Pháo đài nằm trên đồi phía trên thành phố; đá sa thạch vàng trong mười phút rồi đỏ than trong mười phút sau. Gió nổi lên xung quanh hoàng hôn, nhiệt độ giảm, và không khí thoảng mùi bạch đậu khấu từ tiệm gia vị trong con hẻm bên dưới.',
      'Một lưu ý về bảo tồn. Pháo đài đang bị tổn hại. Các bức tường không được thiết kế để hấp thụ lượng nước mà hệ thống ống nước hiện đại rò rỉ vào chúng mỗi ngày. Có một nỗ lực tích cực — quỹ Jaisalmer in Jeopardy — để khôi phục các pháo đài bị hư hại nặng nhất và nâng cấp hệ thống thoát nước. Ở trong pháo đài nếu bạn muốn hỗ trợ công việc đó. Ở ngoài pháo đài nếu bạn muốn nó tồn tại lâu hơn. Không có câu trả lời đúng; cả hai lập luận đều tốt.',
    ],
  },
  {
    slug: 'munnar-mornings',
    title: 'Trà, sương mù, và tầm nhìn xa',
    dest: 'Munnar',
    read: '5 phút',
    hue: 'forest',
    src: '/images/chi-vinh-house-hero.svg',
    author: 'Devika Nair',
    date: 'Tháng 12, 2025',
    excerpt: 'Một bài luận ngắn về những gì đồn điền chè làm với cảm nhận thời gian của bạn.',
    body: [
      'Một đồn điền chè đang hoạt động là nơi thời gian chậm hơn bất kỳ nơi nào tôi từng đến. Những cây chè được cắt tỉa chính xác đến ngang hông. Người hái di chuyển xuống các hàng trong những đường chéo không vội vã. Sương mù từ các sườn cao hơn đến vào khoảng 6:30 sáng và tan vào 8:15, gần như chính xác, mỗi ngày. Không có gì về đồn điền chè muốn bạn phải vội vã.',
    'Một khu nghỉ nhỏ gồm mười hai cabin trên sườn đồi, gần đồn điền chè, phù hợp cho những ai cần tĩnh dưỡng.',
      'Bạn đến vào giờ ăn trưa; nhân viên mang cho bạn trà từng ở trên cây hai ngày trước và được sấy tại nhà máy ở cuối con đường. Hương vị xanh hơn và đậm đà hơn bất kỳ loại trà nào bạn từng uống ngoài châu Á. Họ giải thích — lịch sự, thường xuyên — rằng trà bạn mua ở siêu thị ở nhà chính là thứ *không* đủ tốt để uống ở Munnar.',
      'Bình minh bạn thức dậy vì sương mù dày đặc đến nỗi cửa sổ trắng xóa. Bạn pha cà phê — không có ấm đun, bạn đun nước trên một bếp trại nhỏ ngoài hiên — và ngắm sương mù sắp xếp lại quanh cabin. Đến 8:15 nó biến mất và sườn đồi bên dưới hiện ra, như được vẽ lại tươi mới.',
    'Bạn sẽ được nghỉ ngơi hoàn toàn — đó chính là mục đích của chuyến đi này.',
    ],
  },
];

export const FAQ_GROUPS = [
  {
    title: 'Thuê nhà',
    items: [
      { q: 'Làm thế nào để thuê nhà?', a: 'Tìm nhà cho thuê qua mục Tìm nhà hoặc thanh tìm kiếm trang chủ, chọn ngày và loại nhà, sau đó nhấn Thuê ngay. Bạn sẽ được hướng dẫn qua ba bước — thông tin người thuê, thanh toán, xác nhận. Bạn sẽ không bị tính phí cho đến bước xác nhận.' },
      { q: 'Tôi có thể thuê nhiều nhà cùng lúc không?', a: 'Hiện tại, mỗi lần thuê một nhà. Nếu bạn cần nhiều căn trong cùng một khu vực cho cùng ngày, hãy tạo yêu cầu riêng lẻ — tất cả sẽ hiển thị dưới một hồ sơ người thuê.' },
      { q: 'Chính sách hủy yêu cầu thuê như thế nào?', a: 'Hủy miễn phí trong vòng 48 giờ trước khi nhận nhà. Trong vòng 48 giờ, tháng đầu tiên sẽ bị tính phí. Sau khi nhận nhà, không hoàn tiền — nhưng chủ nhà có thể cung cấp tín dụng cho lần thuê sau; hãy liên hệ trực tiếp với chủ nhà.' },
      { q: 'Tại sao yêu cầu thuê của tôi bị từ chối với thông báo "Nhà đã được thuê"?', a: 'Có hai người cùng yêu cầu một căn nhà cho khoảng thời gian trùng nhau và người kia đã hoàn tất trước. Hãy chọn ngày khác hoặc căn nhà khác.' },
    ],
  },
  {
    title: 'Tài khoản',
    items: [
      { q: 'Tôi quên mật khẩu.', a: 'Tính năng đặt lại mật khẩu chưa hoạt động. Hãy đăng nhập bằng Google hoặc liên hệ với chúng tôi qua trang Liên hệ để được đặt lại thủ công.' },
      { q: 'Tôi có thể có cả tài khoản người thuê và chủ nhà không?', a: 'Có — chúng nằm ở bảng riêng biệt, vì vậy bạn có thể đăng ký cả hai bằng cùng một email. Sử dụng nút chuyển đổi vai trò trên màn hình Đăng nhập để chọn tài khoản muốn đăng nhập.' },
      { q: 'Làm thế nào để xóa tài khoản?', a: 'Gửi email đến contact@chivinhland.example với tiêu đề "Xóa tài khoản của tôi" và chúng tôi sẽ xử lý trong vòng bảy ngày.' },
    ],
  },
  {
    title: 'Thanh toán',
    items: [
      { q: 'Các phương thức thanh toán được chấp nhận?', a: 'Thẻ (Visa, Mastercard), chuyển khoản ngân hàng và thanh toán tại nhà cho những chủ nhà cho phép. Lựa chọn có ở Bước 2 của quy trình thuê nhà.' },
      { q: 'Tại sao thuế lại 10%?', a: 'Đó là thuế VAT áp dụng cho nhà cho thuê tại Việt Nam. Chúng tôi hiển thị mức thuế áp dụng cho căn nhà bạn chọn.' },
      { q: 'Khi nào chủ nhà nhận được tiền?', a: 'Chủ nhà được thanh toán hàng tháng, vào ngày 1, cho tất cả các hợp đồng thuê đã hoàn tất trong tháng trước — sau khi trừ hoàn tiền và phí nền tảng 10% của chúng tôi.' },
    ],
  },
  {
    title: 'Chủ nhà',
    items: [
      { q: 'Làm thế nào để đăng tin cho thuê?', a: 'Đăng ký với vai trò chủ nhà trên màn hình Đăng nhập → chuyển đổi vai trò: Tôi cho thuê nhà. Sau đó, không gian Chủ nhà sẽ hướng dẫn bạn qua ba bước: thông tin cơ bản, địa chỉ + tiện nghi và phòng.' },
      { q: 'Loại nhà nào được chấp nhận?', a: 'Nhà cho thuê độc lập, có cá tính — nhà cổ được phục hồi, nhà gỗ, nhà phố, căn hộ cao cấp. Chúng tôi không nhận nhà cho thuê theo chuỗi.' },
      { q: 'Hoa hồng là bao nhiêu?', a: '10% trên tổng giá trị hợp đồng thuê. Không có phí niêm yết, không phí cố định, không có giá chênh lệch theo giờ cao điểm.' },
    ],
  },
];
